services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pelubot-backend
    working_dir: /app/backend
    env_file:
      - .env
    environment:
      # Valores por defecto; pueden sobreescribirse en .env
      TZ: ${TZ:-Europe/Madrid}
      API_KEY: ${API_KEY?Define API_KEY en .env}
      PUBLIC_RESERVATIONS_ENABLED: ${PUBLIC_RESERVATIONS_ENABLED:-false}
      USE_GCAL_BUSY: ${USE_GCAL_BUSY:-false}
      # Para desarrollo puedes forzar cliente de Google Calendar falso (sin llamadas externas)
      PELUBOT_FAKE_GCAL: ${PELUBOT_FAKE_GCAL:-0}
      # OAuth por defecto apunta a archivo dentro del contenedor
      GOOGLE_OAUTH_JSON: ${GOOGLE_OAUTH_JSON:-/app/backend/tmp}
      # Base de datos SQLite persistente
      DATABASE_URL: ${DATABASE_URL:-sqlite:////app/backend/data/pelubot.db}
    volumes:
      - backend_data:/app/backend/data
      # Monta el directorio temporal que contiene los tokens OAuth
      - ./backend/tmp:/app/backend/tmp
    ports:
      - "${BACKEND_PORT:-8776}:8776"

  frontend:
    build:
      context: .
      dockerfile: Frontend/shadcn-ui/Dockerfile
      args:
        # El frontend compila con base '/api' que nginx proxya al backend
        API_BASE: ${FRONT_API_BASE:-/api}
        # Habilita la ruta de debug y logs de red en la SPA (solo para desarrollo)
        VITE_ENABLE_DEBUG: ${FRONT_ENABLE_DEBUG:-1}
        # Controla uso de Google Calendar (1=activo, 0=desactivado)
        VITE_USE_GCAL: ${FRONT_USE_GCAL:-0}
    container_name: pelubot-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8080}:80"

  frontend-dev:
    image: node:20-alpine
    container_name: pelubot-frontend-dev
    working_dir: /app
    environment:
      # El navegador accede a localhost:8776 desde tu máquina
      - VITE_API_BASE_URL=http://localhost:${BACKEND_PORT:-8776}
      - VITE_ENABLE_DEBUG=1
      - VITE_USE_GCAL=${FRONT_USE_GCAL:-0}
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - ./Frontend/shadcn-ui:/app
      - frontend_node_modules:/app/node_modules
    command: >-
      sh -lc "corepack enable && corepack prepare pnpm@8.10.0 --activate && \
      ([ -d node_modules ] || pnpm install --frozen-lockfile) && pnpm dev --host 0.0.0.0"
    ports:
      - "${FRONTEND_PORT:-8080}:5173"
    depends_on:
      - backend

  e2e:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    container_name: pelubot-e2e
    depends_on:
      - backend
      - frontend
    environment:
      - BASE_URL=http://pelubot-frontend
      - BACKEND_URL=http://pelubot-backend:8776
    volumes:
      - ./e2e/artifacts:/e2e/artifacts

volumes:
  backend_data:
    name: pelubot_db
  frontend_node_modules:
    name: pelubot_frontend_node_modules
